export const SEARCH_FOCUS = 'header/searchFocus'
export const SEARCH_BLUR = 'header/searchBlur'
export const SEARCH_ENTER = 'header/search_enter'
export const SEARCH_LEAVE = 'header/search_leave'
export const PUT_LIST = 'header/put_list'
export const SEARCH_SWITCH = 'header/search_switch'
export const SEARCH_LIST = 'header/search_list'