export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_ITEM = 'add_item'
export const DELETE_ITEM = 'delete_item'
export const INIT_DATA = 'init_data'
export const GET_TODO = 'get_todo'